// export const categories = [
//   "apple",
//   "apps",
//   "climate-change",
//   "creators",
//   "cryptocurrency",
//   "cyber-security",
//   "elon-musk",
//   "film",
//   "facebook",
//   "gadgets",
//   "games",
//   "google",
//   "good-deals",
//   "how-to",
//   "meta",
//   "microsoft",
//   "policy",
//   "reviews",
//   "samsung",
//   "science",
//   "space",
//   "streaming-wars",
//   "tesla",
//   "tiktok",
//   "transportation",
//   "tv",
//   "twitter",
//   "youtube",
// ] as const;

export const categories = {
  apple: "Apple",
  apps: "Apps",
  "climate-change": "Climate",
  creators: "Creators",
  cryptocurrency: "Crypto",
  "good-deals": "Deals",
  "elon-musk": "Elon Musk",
  film: "Film",
  facebook: "Facebook",
  gadgets: "Gadgets",
  games: "Games",
  google: "Google",
  "how-to": "How-to",
  meta: "Meta",
  microsoft: "Microsoft",
  policy: "Policy",
  reviews: "Reviews",
  samsung: "Samsung",
  science: "Science",
  "cyber-security": "Security",
  space: "Space",
  "streaming-wars": "Streaming",
  tesla: "Tesla",
  tiktok: "Tiktok",
  transportation: "Transportation",
  tv: "TV",
  twitter: "Twitter",
  youtube: "Youtube",
} as const;

export type Category = keyof typeof categories;
