name: Update Feed Entries

on:
  # schedule:
  #   - cron: '30 4 * * *'
  workflow_dispatch:

jobs:
  build:
    timeout-minutes: 3
    permissions: read-all

    steps:
    - uses: actions/checkout@v4

    - uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x
    
    - run: |
        deno --version